<?php   $title="Home"; ?>

<?php ob_start(); ?>

<p>
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
Home...    Home...    Home...    Home...    Home...    
</p>


<?php $content = ob_get_clean(); ?>

<?php include 'layout.php'?>