<?php   $title="Mustapha"; ?>

<?php ob_start(); ?>

<p>
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha....
 Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha....
 Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... Mustapha.... 
</p>


<?php $content = ob_get_clean(); ?>

<?php include 'layout.php'?>