<?php   $title="Saadia"; ?>

<?php ob_start(); ?>

<p>
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... Saadia.... 
</p>


<?php $content = ob_get_clean(); ?>

<?php include 'layout.php'?>