<?php   $title="Youssef"; ?>

<?php ob_start(); ?>

<p>
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....Youssef....
</p>


<?php $content = ob_get_clean(); ?>

<?php include 'layout.php'?>